// Generated by npm run build.
const __mfVersion="0.4.1";
let __mfLanguage='en';
const __mfL=(zh,en)=>__mfLanguage==='zh'?zh:en;
const defaults = {
  enabled: true,
  intervalMinutes: 5,
  tweetsPerPage: 5,
  videoCheck: true,
  videoSwitch: true,
  business: '',
  work: ''
};
let presetQueue = Promise.resolve();
let taskQueue = Promise.resolve();
const defaultPurposePresets = () => [{
  code: 'inspiration',
  label: __mfL("\u5BFB\u627E\u7075\u611F", "Find inspiration")
}, {
  code: 'understand',
  label: __mfL("\u4E86\u89E3\u4E00\u4EF6\u4E8B", "Understand a topic")
}, {
  code: 'skill',
  label: __mfL("\u5B66\u4F1A\u4E00\u4E2A\u5C0F\u6280\u5DE7", "Learn one small skill")
}];
async function storedPresets() {
  const {
    presets,
    settings
  } = await chrome.storage.local.get(['presets', 'settings']);
  return {
    purpose: presets?.purpose ?? [],
    business: presets?.business ?? (settings?.business ? [settings.business] : []),
    next: presets?.next ?? [],
    hiddenDefaults: presets?.hiddenDefaults ?? []
  };
}
async function readPresets() {
  const saved = await storedPresets();
  const suggestions = defaultPurposePresets().filter(item => !saved.hiddenDefaults.includes(item.code)).map(item => item.label).filter(label => !saved.purpose.includes(label));
  return {
    ...saved,
    purpose: [...saved.purpose, ...suggestions]
  };
}
chrome.runtime.onMessage.addListener((message, sender, respond) => {
  (async () => {
    __mfLanguage = (await chrome.storage.local.get('language')).language === 'zh' ? 'zh' : 'en';
    const tabKey = `session:${sender.tab?.id}`;
    if (message.type === 'LANGUAGE') {
      if (!['en', 'zh'].includes(message.language)) throw new Error('Invalid language');
      await chrome.storage.local.set({
        language: message.language
      });
      return {
        ok: true
      };
    }
    if (message.type === 'TASKS') return {
      tasks: (await chrome.storage.local.get('tasks')).tasks || []
    };
    if (message.type === 'TASK_EDIT') {
      const operation = taskQueue.then(async () => {
        let tasks = (await chrome.storage.local.get('tasks')).tasks || [];
        let id;
        if (message.action === 'remove') tasks = tasks.filter(card => card.id !== message.id);else if (message.action === 'save') {
          const input = message.card || {},
            card = {};
          for (const [key, limit] of Object.entries({
            purpose: 200,
            stopCondition: 300,
            exitAction: 500
          })) {
            if (typeof input[key] !== 'string' || !input[key].trim() || input[key].trim().length > limit) throw new Error(__mfL("\u8BF7\u586B\u5199\u5B8C\u6574\u7684\u76EE\u7684\u3001\u7ED3\u675F\u6761\u4EF6\u548C\u9000\u51FA\u540E\u884C\u52A8", "Add a purpose, a stopping rule, and a next action."));
            card[key] = input[key].trim();
          }
          if (![5, 10, 20].includes(input.budget)) throw new Error(__mfL("\u8BF7\u9009\u62E9 5\u300110 \u6216 20 \u5206\u949F", "Choose 5, 10, or 20 minutes."));
          card.budget = input.budget;
          if (input.id && !tasks.some(task => task.id === input.id)) throw new Error(__mfL("\u8FD9\u5F20\u5361\u5DF2\u88AB\u5220\u9664\uFF0C\u8BF7\u4FDD\u5B58\u4E3A\u65B0\u4EFB\u52A1\u5361", "This card was removed. Save it as a new task card."));
          if (!input.id && tasks.length >= 30) throw new Error(__mfL("\u6700\u591A\u4FDD\u5B58 30 \u5F20\u4EFB\u52A1\u5361", "You can save up to 30 task cards."));
          id = card.id = input.id || crypto.randomUUID();
          const index = tasks.findIndex(task => task.id === id);
          if (index >= 0) tasks[index] = card;else tasks.push(card);
        } else throw new Error(__mfL("\u4EFB\u52A1\u5361\u64CD\u4F5C\u65E0\u6548", "Invalid task card operation."));
        await chrome.storage.local.set({
          tasks
        });
        return {
          tasks,
          id
        };
      });
      taskQueue = operation.catch(() => {});
      return operation;
    }
    if (message.type === 'PRESETS') return {
      presets: await readPresets()
    };
    if (message.type === 'PRESET_EDIT') {
      const operation = presetQueue.then(async () => {
        const limit = {
          purpose: 200,
          business: 200,
          next: 500
        }[message.kind];
        const value = typeof message.value === 'string' ? message.value.trim() : '';
        if (!limit || !value || value.length > limit || !['add', 'remove'].includes(message.action)) throw new Error(__mfL("\u5FEB\u6377\u9009\u9879\u5185\u5BB9\u65E0\u6548", "Invalid preset."));
        const presets = await storedPresets();
        const visible = (await readPresets())[message.kind];
        if (message.action === 'add') {
          if (!visible.includes(value)) {
            if (visible.length >= 30) throw new Error(__mfL("\u6BCF\u7C7B\u6700\u591A\u4FDD\u5B58 30 \u4E2A\u5FEB\u6377\u9009\u9879", "You can save up to 30 presets per category."));
            presets[message.kind].push(value);
          }
        } else {
          presets[message.kind] = presets[message.kind].filter(item => item !== value);
          if (message.kind === 'purpose') for (const item of defaultPurposePresets()) if (item.label === value && !presets.hiddenDefaults.includes(item.code)) presets.hiddenDefaults.push(item.code);
        }
        await chrome.storage.local.set({
          presets
        });
        return {
          presets: await readPresets()
        };
      });
      presetQueue = operation.catch(() => {});
      return operation;
    }
    if (message.type === 'INIT') {
      const saved = await chrome.storage.local.get('settings');
      const current = (await chrome.storage.session.get(tabKey))[tabKey];
      return {
        settings: {
          ...defaults,
          ...saved.settings
        },
        session: current && Date.now() - current.updated < 30 * 60 * 1000 ? current : null
      };
    }
    if (message.type === 'SESSION' && sender.tab) {
      await chrome.storage.session.set({
        [tabKey]: {
          ...message.session,
          updated: Date.now()
        }
      });
      return {
        ok: true
      };
    }
    if (message.type === 'SAVE') {
      const entry = {
        ...message.entry,
        id: /^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(message.entry?.clientId || '') ? message.entry.clientId : crypto.randomUUID(),
        created: new Date().toISOString(),
        done: false
      };
      await chrome.storage.local.set({
        [`entry:${entry.id}`]: entry
      });
      return {
        ok: true
      };
    }
    if (message.type === 'WORK' && sender.tab) {
      await chrome.storage.session.remove(tabKey);
      const action = typeof message.action === 'string' ? message.action.trim().slice(0, 500) : '';
      const handoff = crypto.randomUUID();
      await chrome.storage.session.set({
        [`work:${handoff}`]: {
          action,
          created: Date.now()
        }
      });
      await chrome.tabs.update(sender.tab.id, {
        url: chrome.runtime.getURL(`dashboard.html?handoff=${handoff}#work`)
      });
      return {
        ok: true
      };
    }
    if (message.type === 'DASHBOARD') {
      await chrome.tabs.create({
        url: chrome.runtime.getURL('dashboard.html')
      });
      return {
        ok: true
      };
    }
    throw new Error(__mfL("\u4E0D\u652F\u6301\u7684\u64CD\u4F5C", "Unsupported operation."));
  })().then(respond, error => respond({
    error: error.message
  }));
  return true;
});
chrome.tabs.onRemoved.addListener(tabId => chrome.storage.session.remove(`session:${tabId}`));
