const fs=require('node:fs'),path=require('node:path');
const {marked}=require('marked');
const root=path.resolve(__dirname,'..');
const files=['README.md','README.zh-CN.md','docs/why-intent-first.md','docs/why-intent-first.zh-CN.md','PRIVACY.md','VALIDATION.md'];
const docs=Object.fromEntries(files.map(file=>[file,marked.parse(fs.readFileSync(path.join(root,file),'utf8')).replace(/href="\.\.\//g,'href="').replace(/href="why-intent-first/g,'href="docs/why-intent-first')]));
const payload=JSON.stringify(docs).replace(/</g,'\\u003c');
const html=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Intent First — 发布前预览</title><style>
:root{font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#19382e;background:#f5f4ee;line-height:1.75}*{box-sizing:border-box}body{margin:0}.top{border-bottom:1px solid #d9e1d7;background:#fff;position:sticky;top:0;z-index:2}.top-inner{max-width:1060px;margin:auto;padding:16px 28px;display:flex;gap:18px;align-items:center;justify-content:space-between;flex-wrap:wrap}.name{font-size:18px;font-weight:750;letter-spacing:.2px}.badge{font-size:12px;border:1px solid #e2c98f;border-radius:100px;padding:3px 10px;color:#886426;background:#fcf8ed}.intro{max-width:1060px;margin:auto;padding:44px 28px 22px}.eyebrow{font-size:12px;letter-spacing:2px;color:#63796c}.intro h1{font-size:36px;line-height:1.2;margin:12px 0}.intro p{color:#627468;margin:10px 0}.controls{display:flex;gap:8px;flex-wrap:wrap;margin:22px 0 0}button,.action{font:inherit;font-size:14px;border:1px solid #bbccbf;color:#234f41;background:#fff;padding:9px 14px;border-radius:9px;cursor:pointer;text-decoration:none}button[aria-pressed=true],.action.primary{background:#234f41;color:white;border-color:#234f41}button:focus-visible,a:focus-visible{outline:3px solid #d89558;outline-offset:3px}.sheet{max-width:1004px;margin:0 auto 56px;padding:40px 64px;background:#fff;border:1px solid #dbe2d8;border-radius:18px}.sheet h1{font-size:34px;line-height:1.3;margin-top:0}.sheet h2{font-size:24px;margin-top:36px;padding-bottom:8px;border-bottom:1px solid #e4e9e1}.sheet h3{font-size:19px;margin-top:26px}.sheet p,.sheet li{color:#334a40}.sheet a{color:#266d53;text-underline-offset:3px}.sheet img{max-width:100%;border:1px solid #dce4da;border-radius:12px;display:block;margin:26px auto}.sheet blockquote{margin:22px 0;padding:10px 20px;background:#edf3eb;border-left:4px solid #39735a;border-radius:0 8px 8px 0}.sheet pre{background:#f2f5ef;border-radius:10px;padding:16px;overflow:auto}.sheet code{font-size:.9em;background:#f2f5ef;padding:2px 4px;border-radius:4px}.sheet table{border-collapse:collapse;width:100%}.sheet td,.sheet th{border:1px solid #dbe2d8;padding:8px}.footer{max-width:1004px;margin:0 auto 50px;padding:0 28px;color:#6a7a70;font-size:13px}@media(max-width:700px){.intro{padding:28px 18px 18px}.intro h1{font-size:28px}.sheet{border-radius:0;padding:24px 20px}.top-inner{padding:12px 18px}.sheet h1{font-size:28px}}
</style></head><body><header class="top"><div class="top-inner"><div class="name">Intent First <span style="font-weight:400;color:#809085">/ 醒一下</span></div><span class="badge">本地草稿 · 尚未发布到 GitHub</span></div></header><section class="intro"><div class="eyebrow">REVIEW BEFORE PUBLISHING</div><h1>先看一遍，再决定发布。</h1><p>英文 README、中文对照、创作缘由文章，以及可以实际操作的双语演示。</p><div class="controls"><button data-doc="README.md" aria-pressed="false">English README</button><button data-doc="README.zh-CN.md" aria-pressed="false">中文 README</button><button data-doc="docs/why-intent-first.md" aria-pressed="false">English article</button><button data-doc="docs/why-intent-first.zh-CN.md" aria-pressed="false">中文文章</button></div><div class="controls"><a class="action primary" href="extension/demo.html?surface=x&lang=en" target="_blank" rel="noopener">Try English demo ↗</a><a class="action" href="extension/demo.html?surface=x&lang=zh" target="_blank" rel="noopener">体验中文演示 ↗</a></div></section><article id="document" class="sheet"></article><footer class="footer">预览对应拟建仓库 intent-first。尚未创建仓库、上传文件或提交个人资料修改。演示与配图使用示例数据。</footer><script>
const docs=${payload};const output=document.querySelector('#document');
function show(file){if(!docs[file])return;output.innerHTML=docs[file];document.querySelectorAll('[data-doc]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.doc===file)));history.replaceState(null,'','#'+file);}
document.querySelectorAll('[data-doc]').forEach(button=>button.onclick=()=>show(button.dataset.doc));
output.onclick=event=>{const a=event.target.closest('a');if(!a)return;const href=a.getAttribute('href');const [file,fragment]=href.split('#');if(docs[file]){event.preventDefault();show(file);if(fragment){const h=[...output.querySelectorAll('h1,h2,h3')].find(el=>el.textContent.toLowerCase().replace(/[^a-z0-9 ]/g,'').replace(/ /g,'-')===fragment);h?.scrollIntoView();}}};
show(decodeURIComponent(location.hash.slice(1))||'README.md');
</script></body></html>`;
fs.writeFileSync(path.join(root,'preview.html'),html);
console.log('Preview written to preview.html');
